services:
    liip_hello.world.controller:
        class: Liip\HelloBundle\Controller\HelloController
        arguments:
            view: @fos_rest.view

    liip_hello.phpcr.controller:
        class: Liip\HelloBundle\Controller\PHPCRController
        interfaceInjectionEnabled: false
        calls:
            - ['setContainer', [ @liip_hello.container ] ]

    liip_hello.container:
        parent: liip_container_wrapper.service
        arguments:
            index_0:
                doctrine.phpcr_odm.document_manager: true
                my_view: fos_rest.view

    # Temporary fix since ContainerWrapperBundle is broken atm because of interface injection
    # See the following url for details: http://groups.google.com/group/symfony-devs/browse_thread/thread/efb1b1588f05f255
    my_view:
        alias: fos_rest.view
