services:
    liip_hello.world.controller:
        class: Liip\HelloBundle\Controller\HelloController
        arguments:
            view: @fos_rest.view
            validator: @validator

    liip_hello.rest.controller:
        class: Liip\HelloBundle\Controller\RestController
        arguments:
            request: @request
            session: @session
            view: @fos_rest.view
            formFactory: @form.factory
        scope: request

    liip_hello.phpcr.controller:
        class: Liip\HelloBundle\Controller\PHPCRController
        calls:
            - ['setContainer', [ @liip_hello.container ] ]

    liip_hello.container:
        parent: liip_container_wrapper.service
        arguments:
            index_0:
                doctrine_phpcr.odm.document_manager: true
                my_view: fos_rest.view

    liip_hello.vie.controller:
        class: Liip\HelloBundle\Controller\VieController
        arguments:
            view: @fos_rest.view
            request: @liip_hello.article.repository

    liip_hello.article.repository:
        class: Doctrine\ODM\PHPCR\DocumentRepository
        factory_service: doctrine_phpcr.odm.document_manager
        factory_method: getRepository
        arguments:
            document_class_name: Liip\HelloBundle\Document\Article
