services:
    liip_hello.world.controller:
        class: Liip\HelloBundle\Controller\HelloController
        arguments:
            view: @fos_rest.view
            validator: @validator

    liip_hello.rest.controller:
        class: Liip\HelloBundle\Controller\RestController
        arguments:
            view: @fos_rest.view

    liip_hello.phpcr.controller:
        class: Liip\HelloBundle\Controller\PHPCRController
        calls:
            - ['setContainer', [ @liip_hello.container ] ]

    liip_hello.container:
        parent: liip_container_wrapper.service
        arguments:
            index_0:
                doctrine.phpcr_odm.document_manager: true
                my_view: fos_rest.view

    liip_hello.get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer

    liip_hello.violation_list_normalizer:
        class: FOS\RestBundle\Serializer\Normalizer\ValidatorConstraintViolationListNormalizer
