services:
    liip_hello.controller:
        class: Liip\HelloBundle\Controller\HelloController
        arguments:
            view: @fos_rest.view
        calls:
            - ['setContainer', [ @service_container ] ]
