hello:
    pattern:  /liip/hello/{name}.{_format}
    defaults: { _controller: liip_hello.world.controller:indexAction, _format: html }

hello_fallback:
    pattern:  /liip/hello
    defaults: { _controller: liip_hello.world.controller:indexAction, _format: html }

hello_serializer:
    pattern:  /liip/serializer.xml
    defaults: { _controller: liip_hello.world.controller:serializerAction, _format: xml }

hello_facebook:
    pattern:  /liip/facebook
    defaults: { _controller: liip_hello.world.controller:facebookAction, _format: html }

hello_exception:
    pattern:  /liip/exception.{_format}
    defaults: { _controller: liip_hello.world.controller:exceptionAction, _format: html }

hello_validation_failure:
    pattern:  /liip/validation_failure.json
    defaults: { _controller: liip_hello.world.controller:validationFailureAction, _format: json }

hello_facebook_check:
    pattern:  /liip/facebook-check
    defaults: { _controller: liip_hello.world.controller:facebookAction, _format: html }

hello_facebook_logout:
    pattern:  /liip/facebook-logout
    defaults: { _controller: liip_hello.world.controller:facebookAction, _format: html }

hello_phpcr:
    pattern:  /liip/phpcr/{title}
    defaults: { _controller: liip_hello.phpcr.controller:indexAction, _format: html }

extra:
    resource: "@LiipHelloBundle/Controller/ExtraController.php"
    type:     annotation

rest:
    resource: liip_hello.rest.controller
    type:     rest
