hello:
    pattern:  /liip/hello/{name}.{_format}
    defaults: { _controller: liip_hello.controller:indexAction, _format: html }

hello_fallback:
    pattern:  /liip/hello
    defaults: { _controller: liip_hello.controller:indexAction, _format: html }

hello_phpcr:
    pattern:  /liip/phpcr/{path}
    defaults: { _controller: liip_hello.controller:phpcrAction, _format: html }

hello_serializer:
    pattern:  /liip/serializer.xml
    defaults: { _controller: liip_hello.controller:serializerAction, _format: xml }

hello_facebook:
    pattern:  /liip/facebook
    defaults: { _controller: liip_hello.controller:facebookAction, _format: html }

hello_facebook_check:
    pattern:  /liip/facebook-check
    defaults: { _controller: liip_hello.controller:facebookAction, _format: html }
