hello:
    pattern:  /liip/hello/{name}.{_format}
    defaults: { _controller: liip_hello.controller:indexAction, _format: html }

hello_fallback:
    pattern:  /liip/hello
    defaults: { _controller: liip_hello.controller:indexAction, _format: html }
